FROM python:3.9-bookworm
MAINTAINER Chu
WORKDIR /GUI
ADD ./GUI /GUI
RUN pip install --upgrade pip
ADD ./requirements.txt /GUI
RUN pip install -r requirements.txt
RUN pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu118

